import Head from "next/head"
import Layout from "@/components/molecules/Layout"
import Grid from "@/components/atom/Grid"
import Navbar from "@/components/organisme/Navbar"
import TextTitle from "@/components/molecules/TextTitlte"
import ImagePrimary from "@/components/molecules/Image/Image"
import Button from "@/components/atom/Button"
import ButtonText from "@/components/atom/ButtonText"
import Footer from "@/components/organisme/Footer"
import TabBusiness from "@/components/organisme/TabBusiness"
import ImagePricing from "@/assets/ImagePricing.png"

const office = () => {
    return(
        <>
        <Head>
            <title>MyCap - For Organizations</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <Layout className="mt-24">
            <TabBusiness />
            <Grid mt="mt-60">
                <ImagePrimary
                    link = {ImagePricing}
                    alt = "Pricing"
                />
                <TextTitle
                    title = "MyGlasses Untuk Bisnis"
                    body = "Penerjemah dengan fitur lengkap untuk interaksi yang lebih baik, dengan harga yang baik untuk kinerja optimal"
                >
                    <div className="flex flex-row items-center gap-x-5 mt-10"> 
                        <Button
                            title = "Coba Versi Demo"
                            className = "rounded-full bg-secondary-teal font-regular text-white text-sm md:text-base"
                        />
                        <ButtonText title="atau" link="Lihat Harga" url="/"/>
                    </div>
                </TextTitle>
            </Grid>
            <div className="flex justify-center">
                    <div className="text-center mt-10 w-1/2">
                        <p>Anda juga bisa mengunduh MyGlasses versi Mobile App</p>
                        <Button
                            title = "Download"
                            className = "rounded-full bg-secondary-teal font-regular text-white mt-8 text-sm md:text-base"
                        />
                    </div>
                </div>
        </Layout>
        <Footer />
        </>
    )
}

export default office