import React, { useState } from "react";
import Head from "next/head";
import NavbarLogin from "@/components/organisme/NavbarLogin";
import Layout from "@/components/molecules/Layout";
import ButtonImg from "@/components/molecules/ButtonImg";
import Button from "@/components/atom/Button";
import iconlogin from "@/assets/icon-login.png"
import Input from "@/components/atom/Input";
import { useRouter } from "next/router";
import { useAccount } from "@/service/appwrite/query/useAccount";
const Registration = () => {

  const [user, setUser] = useState('');
  const [password, setPassword] = useState('');
  const [email, setEmail] = useState('');
  const router = useRouter();
  const {login, register} = useAccount();

  const handleRegis = async (e) => {
    e.preventDefault();
    try {
        await register(email, password, user);
        await login(email, password)
            .finally(() => router.push("/chat"));
    }
    catch(e) {
      console.log(e);
    }

  }

  return (
    <>
        <Head>
            <title>MyCap - Registration</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <NavbarLogin />

        <Layout
            className="flex justify-center"
        >
            <div className="mt-8 shadow-2xl p-9 rounded-xl md:min-w-[728px]">
                <p className="font-bold text-4xl text-gray-700 dark:text-white">Daftar</p>

                <div className="mt-9 md:px-36 px-4">
                  <Input type="text" placeholder="Username" value={user} onChange={(e) => setUser(e.target.value)} />
                  <Input type="email" placeholder="Email" value={email} onChange={(e) => setEmail(e.target.value)} />
                  <Input type="password" placeholder="Password" value={password} onChange={(e) => setPassword(e.target.value)} />
                </div>

                <div className="mt-14 flex justify-between gap-4">
                    <Button title="Login Nanti (as guest)" className="bg-primary-gray font-medium text-primary-teal rounded-full"/>
                    <div onClick={(e) => handleRegis(e)}>
                        <ButtonImg img={iconlogin} onClick={handleRegis} 
                        title="Daftar"
                        backGround="bg-secondary-teal"
                        textColor="text-white dark:text-white"
                        padding="md:p-4 p-2"
                        />
                    </div>
                </div>
            </div>
        </Layout>
      </>
  )
}

export default Registration;