import { RootContext } from '@/service/context/Context'
import Head from 'next/head'
import Image from 'next/image';
import { useTheme } from "next-themes";

import ImageWork from "@/assets/work.png";
import Sound from "@/assets/sound.png"
import Grouping from '@/assets/grouping.png'
import Conference from '@/assets/conference.png'
import Trancribe from '@/assets/trancribe.png'

import { useContext, useEffect, useState } from 'react'
import Navbar from '@/components/organisme/Navbar'
import Layout from '@/components/molecules/Layout';
import Grid from '@/components/atom/Grid';
import ButtonImg from '@/components/molecules/ButtonImg';
import Button from '@/components/atom/Button';
import CircleCard from '@/components/molecules/CircleCard';
import Footer from '@/components/organisme/Footer';

import { setDarkMode } from '@/utils/darkmode';
import Advertise from '@/components/molecules/Modals';
import { useRouter } from 'next/router';

export default function Home() {
  const context = useContext(RootContext);
  const {state, dispatch} = context;
  const router = useRouter()
  const {theme, setTheme} = useTheme();
  const [mounted, setMounted] = useState(false);
  console.log(state)

  useEffect(() => {
    setDarkMode(theme);
    setMounted(true);
  }, [])

  const toAuth = () => {
    router.push("/auth/login")
  }

  if(!mounted) return null;

  return (
    <>
      <Head>
        <title>Tulibot V2</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Advertise /> */}
      <Navbar />
      <Layout
        className = "md:mt-32 mt-24 overflow-x-hidden"
      >
        <Grid>
          <div>
            <h1 className='text-5xl text-center md:text-start dark:text-white'>Bebas Berinteraksi</h1>
            <p className='mt-5 dark:text-slate-400'>Aplikasi untuk membantu penyandang tunarungu dalam berkomunikasi kelompok sebagai <span className='font-bold'>solusi Indonesia yang inklusif dan ramah disabilitas</span></p>
            <div className='md:flex mt-14 grid md:justify-start justify-center gap-4 items-center' >
              <ButtonImg 
                onClick = {toAuth}
                img = {Sound}
                backGround = "bg-primary-sky opacity-75 hover:opacity-100 dark:bg-primary-teal dark:opacity-100 dark:hover:opacity-75"
                title = "Mulai Mic"
                className ="rounded-full"
                textColor="text-white dark:text-white"
                textSize="dark:font-medium"
                padding="py-3 px-8"
              />
              <span className='w-full md:w-7 text-center'>atau</span> 
              <Button 
                title = 'lihat solusi lain'
                className ='bg-primary-cyan text-primary-teal font-medium'
              />
            </div>
          </div>
          <div>
            <Image src={ImageWork} alt="image" className=''/>
          </div>
        </Grid>
        <div className='mt-36 text-center dark:text-slate-400'>
          Tulibot memiliki akurasi sistem mencapai <span className='font-semibold dark:text-white'>98,7%</span>
        </div>
        <div className='flex justify-center'>
          <div className="flex md:gap-12 gap-14 mt-32 overflow-x-auto no-scrollbar">
            <CircleCard 
              img = {Grouping}
              title ='Group Chat'
              body = 'Berinteraksi dengan kelompok'
              style = "md:w-44 w-24"
              className="items-center gap-y-2 pt-2"
              bodyWidth="w-96"
            />
            <CircleCard 
              img = {Conference}
              title ='Conference'
              body = 'Konferensi untuk semua orang dengan Tulibot Room '
              style = "md:w-44 w-24"
              className="items-center gap-y-2 pt-2"
              bodyWidth="w-96"
            />
            <CircleCard 
              img = {Trancribe}
              title ='Live Transcribe'
              body = 'Penerjemah suara dan bahasa isyarat menjadi bentuk teks '
              style = "md:w-44 w-24"
              className="items-center gap-y-2 pt-2"
              bodyWidth="w-96"
            />
          </div>
        </div>
        <div className='mt-32 flex justify-center'>
          <p className='text-center md:w-1/2 dark:text-slate-400'>
            Realisasi dalam mewujudkan Tulibot ini membutuhkan partisipasi dari berbagai pihak seperti: Pemerintah (PPDI), Komunitas Tunarungu, dan Pengembang, Peneliti, atau Akademisi
          </p>
        </div>
      </Layout>
      <Footer />
    </>
  )
}
