export const  Action = {
  ADD_GROUP : "ADD_GROUP",
  ADD_PROFIL : "ADD_PROFIL",
  SET_PROFILE : "SET_PROFILE",
  ADD_ITEM : "ADD_ITEM",
  DELETE_CHAT : "DELETE_CHAT",
  ADD_CHAT : "ADD_CHAT",
  SET_SOCKET : "SET_SOCKET",
  SR: {  // Speech Recognition
    SET : "SET_SPEECH_RECOGNITION",
    RESET: "RESET_SR_STATES",
    TEMP_RESULT: {
      ADD_TEMP_TRANSCRIPT: "ADD_TEMP_TRANSCRIPT",
      SET_TEMP_TRANSCRIPT: "SET_TEMP_TRANSCRIPT",
      ADD_FINAL_TRANSCRIPT_TEXT: "ADD_FINAL_TRANSCRIPT_TEXT",
      SET_FINAL_TRANSCRIPT_TEXT: "SET_FINAL_TRANSCRIPT_TEXT",
      ADD_FINAL_TRANSCRIPT: "ADD_FINAL_TRANSCRIPT",
      SET_FINAL_TRANSCRIPT: "SET_FINAL_TRANSCRIPT"
    },
    RESULT: {
      ADD: "ADD_FINAL_TRANSCRIPT_RESULT",
      SEND: "SEND_FINAL_TRANSCRIPT_RESULTS"
    }
  },
  MESSAGE : {
    ADD: "ADD_RECEIVED_MESSAGE",
  },
  FINAL_MESSAGES : {
    ADD : "ADD_FINAL_MESSAGES",
  },
  TEMP_MESSAGES : {
    ADD : "ADD_TEMP_MESSAGES",
    SET : "SET_TEMP_MESSAGES",
  },
  GETID : {
    GET : "GET_ID"
  }
}